chore: update python version for runner to 3.12

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,46 +23,46 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.11"]
+        python-version: ["3.12"]
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install and configure Poetry
-      uses: snok/install-poetry@v1
-      with:
-        version: 2.1.2
-        virtualenvs-create: true
-        virtualenvs-in-project: false
-        virtualenvs-path: ~/.virtualenvs
-        installer-parallel: true
-    - name: Install dependencies
-      run: |
-        poetry install
-        poetry run pip install robotframework-browser robotframework-seleniumlibrary
-        poetry run rfbrowser init
-        npx playwright install-deps
-      if: steps.cache.outputs.cache-hit != 'true'
-    - name: Run tests
-      run: |
-        poetry run invoke tests
-    - name: Store Artifact
-      uses: actions/upload-artifact@v4
-      if: success() || failure()
-      with:
-        name: test-results ${{ matrix.python-version }} # Choose a descriptive name for your artifact
-        path: |
-          results/*.html
-          results/*.xml
-          results/*.prof
-          results/*.txt
-    - name: Test Report
-      uses: dorny/test-reporter@v2
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: xUnit Tests ${{ matrix.python-version }}            # Name of the check run which will be created
-        path: results/pytest.xml,results/xunit.xml    # Path to test results
-        reporter: java-junit        # Format of test results
+      - uses: actions/checkout@v3
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install and configure Poetry
+        uses: snok/install-poetry@v1
+        with:
+          version: 2.1.2
+          virtualenvs-create: true
+          virtualenvs-in-project: false
+          virtualenvs-path: ~/.virtualenvs
+          installer-parallel: true
+      - name: Install dependencies
+        run: |
+          poetry install
+          poetry run pip install robotframework-browser robotframework-seleniumlibrary
+          poetry run rfbrowser init
+          npx playwright install-deps
+        if: steps.cache.outputs.cache-hit != 'true'
+      - name: Run tests
+        run: |
+          poetry run invoke tests
+      - name: Store Artifact
+        uses: actions/upload-artifact@v4
+        if: success() || failure()
+        with:
+          name: test-results ${{ matrix.python-version }} # Choose a descriptive name for your artifact
+          path: |
+            results/*.html
+            results/*.xml
+            results/*.prof
+            results/*.txt
+      - name: Test Report
+        uses: dorny/test-reporter@v2
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: xUnit Tests ${{ matrix.python-version }} # Name of the check run which will be created
+          path: results/pytest.xml,results/xunit.xml # Path to test results
+          reporter: java-junit # Format of test results
